name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6.0.2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v4
      
    - name: Restore NuGet Packages
      run: nuget restore osukps.sln

    - name: Build Application
      run: msbuild osukps.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: osukps-release
        path: osukps/bin/
